---
default: true

MD004:
  style: dash

MD013:
  line_length: 120
  heading_line_length: 120
  code_blocks: false

MD024:
  siblings_only: true

MD033:
  allowed_elements:
    - br
    - kdb
    - pre
    - script
    - EnvVar
    - EnvVarSection

MD034: false

MD049:
  style: asterisk

MD060:
  style: padded
